### ISSUE TITLE
Appending window.location.href to fill and clip refs not working in Chrome

### ISSUE THREAD

**Issue by stephencarr** [NetanelBasal/ngx-content-loader#28]
When `window.location.href` is appended to fill and clipping refs and a hash is already in the URL the refs do not work. I don't know why the full href is needed, works perfectly fine with just a conventional ID hash reference.

https://github.com/NetanelBasal/ngx-content-loader/blob/504a105d5e5670ba06fe76db2d921866847463ff/projects/netbasal/ngx-content-loader/src/lib/content-loader.component.ts#L51

**Comment by NetanelBasal** [comment]
Check the original repo. Is it doing the same?

**Comment by stephencarr** [comment]
Nope: https://github.com/danilowoz/react-content-loader/blob/fb0e65b1d64039cac2c9e20c1683e12551d6109d/src/Svg.js#L54

**Comment by fperera123** [comment]
Here this not appended style tag too. Only when in a route path. After removing window.location.href path and adding style to gradient working fine. I checked with with an auxiliary route and no route only. (Chorme)

**Comment by nonsocode** [comment]
#31 
This PR fixes this issue
