### ISSUE TITLE
Update @netbasal/content-loader peer dependencies to angular 7

### ISSUE THREAD

**Issue by Need-To-Learn** [NetanelBasal/ngx-content-loader#29]
Hi,
ngx-content-loader works fine on angular 7, but it would be great to update his peer dependencies to angular 7 to avoid npm warnings.

```
npm WARN @netbasal/content-loader@2.0.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @netbasal/content-loader@2.0.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

Ideally, others npm packages use corresponding package version with angular aka: 
ngx-content-loader@7.0.0 for angular 7 or ngx-content-loader@6.0.0 for angular 6

Thx !

**Comment by NetanelBasal** [comment]
Try v2.1.0

**Comment by Need-To-Learn** [comment]
Hi,
Awesome, thx !
@danielsogl Thx for the PR :)

**Comment by bleuscyther** [comment]
@NetanelBasal when i try to use npm i have this error: 
```Could not install from "netbasal\ngx-content-loader@2.1.0" as it does not contain a package.json file.```
