### ISSUE TITLE
feat: Angular 8 support

### ISSUE THREAD

**Issue by alexw10** [NetanelBasal/ngx-content-loader#34]
If don't have time to do this let me know and I can take a look into getting dependencies updated.

**Comment by NetanelBasal** [comment]
Sure, go for it. Thanks.

**Comment by jbweb** [comment]
Following this...

**Comment by alexw10** [comment]
#35 is the PR

**Comment by alexw10** [comment]
Looks like PR was merged, will a new release be happening for this soon @NetanelBasal ?

**Comment by NetanelBasal** [comment]
Published.
