### ISSUE TITLE
baseUrl input not present

### ISSUE THREAD

**Issue by alexw10** [NetanelBasal/ngx-content-loader#37]
This is related to #36 and or a continuation of it since it got closed.
I still do not see this working even with doing the what your link in #36 says
Things I tried:
Removing <base> completely which then angular 8 (not sure about previous versions) gives this 
```Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.```

I provide the APP_BASE_HREF in the module which gets the error gone but the svgs still are not being renderd.

I think the proper solution is an @Input() for the base url property which is what this added.
https://github.com/danilowoz/react-content-loader/issues/93

Without baseUrl it seems cannot have the `<base href="/">` which Angular 8 seems to complain about it not being there.
Unless I am missing something?

Thoughts?

**Comment by NetanelBasal** [comment]
Yes, we need to mimic the React version.
