### ISSUE TITLE
Add README in npm page

### ISSUE THREAD

**Issue by caroso1222** [NetanelBasal/ngx-content-loader#4]
Seems like you missed to include the README.md when you ran `npm publish` so [the npm page](https://www.npmjs.com/package/@netbasal/content-loader) of the library shows an empty description. This is a problem I just caught within the `ng-lib-schematics` you used to generate the library. I'll open a PR adding that to the build workflow. For now I suggest you to create a new patch version and manually include README.md inside dist, then publish the new version.

<img width="765" alt="screen shot 2018-04-02 at 12 47 30 am" src="https://user-images.githubusercontent.com/3689856/38184752-7222fa5a-360f-11e8-8b93-0bc2357dd140.png">

As mentioned [here](https://github.com/npm/npm/issues/2641#issuecomment-7141407) having a proper README in the npm registry is good to appear on npm searches, and I guess that ranks your library as well in search engines.

**Comment by NetanelBasal** [comment]
Thanks!
