### ISSUE TITLE
Content Loader render black block of svg

### ISSUE THREAD

**Issue by hoangan310** [NetanelBasal/ngx-content-loader#40]
I've made an example on [CodeSandbox](https://codesandbox.io/s/angular-0il6o)
It will render normal if the url don't have the query params.

![image](https://user-images.githubusercontent.com/30396830/59188355-a540e580-8ba1-11e9-8832-0e741f4fd7df.png)

But when have any **query params**, it will show black block instead of svg we need.
Please see the image below.
![image](https://user-images.githubusercontent.com/30396830/59188298-88a4ad80-8ba1-11e9-89c9-b299a2ea10fa.png)
It's happen on **safari** 
Thanks!

**Comment by NetanelBasal** [comment]
Could you please check the original repo?

**Comment by hoangan310** [comment]
[CodeSandbox](https://codesandbox.io/s/frosty-meadow-8q42g)
[React content loader](https://github.com/danilowoz/react-content-loader) not have that problem

**Comment by hoangan310** [comment]
@NetanelBasal 
I found the solution in this [https://stackoverflow.com/questions/49409414/svg-pattern-not-working-in-safari](https://stackoverflow.com/questions/49409414/svg-pattern-not-working-in-safari).
So I closed this issue. 
Thanks!

**Comment by DaSchTour** [comment]
@NetanelBasal I think the documentation is a bit miss-leading here. It tells to use window.location.pathname although that will not work, instead window.location.href needs to be used as stated in the stackoverflow mentioned by @hoangan310
