### ISSUE TITLE
AOT not supported

### ISSUE THREAD

**Issue by JonnyHeavey** [NetanelBasal/ngx-content-loader#5]
The library fails to build when an angular application is built with AOT (https://angular.io/guide/aot-compiler) enabled (such as --prod setup with the angular cli). The following error occurs:

ERROR in ./node_modules/@netbasal/content-loader/content-loader.ngfactory.js
Module not found: Error: Can't resolve 'content-loader' in '/path/to/application/node_modules/@netbasal/content-loader'

**Comment by NetanelBasal** [comment]
Thanks for the report, I'm investigating.

**Comment by NetanelBasal** [comment]
fixed in 1.0.2.

**Comment by JonnyHeavey** [comment]
Thanks for the swift turn around, and the creation of the lib!
