### ISSUE TITLE
error when run ng build --prod ANGULAR 5

### ISSUE THREAD

**Issue by fernandobd42** [NetanelBasal/ngx-content-loader#6]
ERROR in ./node_modules/@netbasal/content-loader/content-loader.ngfactory.js
Module not found: Error: Can't resolve 'content-loader' in '/Users/fernandolucasgontijo/Documents/Nagro/frontend/node_modules/@netbasal/content-loader'

**Comment by NetanelBasal** [comment]
fixed in latest version => 1.0.2
